### ISSUE TITLE
Lenna image considered non-DFSG compliant

### ISSUE THREAD

**Issue by ghisvail** [rjw57/dtcwt#110]
Hi Rich,

Whilst working on the Debian packaging of dtcwt, I hit the following error [1] wrt the embedded Lena image distributed in the source tree under matlab/lena.mat. Apparently, the licensing of Lena images is non-free, though distribution is allowed.

Would you be inclined to changing this file for something else that is DFSG compliant? That would simplify things on my end.

Cheers,
Ghis

[1] https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html

**Comment by rjw57** [comment]
Unfortunately this image is required by the test suite since the output is one of the test vectors I have from the "gold" MATLAB implementation. How annoying is it to strip it out of the package at the Debian end? If the answer is greater than "somewhat", I can see what I can do but it'll require getting another "known good" result from the MATLAB implementation which'll require a bit of work on this end.

**Comment by rjw57** [comment]
I've no problem with replacing the image BTW, I just want to work out which of us would have the bigger task.

**Comment by ghisvail** [comment]
Well, I manage to get around it, since:

https://packages.debian.org/source/sid/python-dtcwt

But, as you may guess from the +dfsg suffix, this requires a repack of the source tree. This is just one additional step between merges, so not a huge effort on my end.

It's my duty as package maintainer to report upstream (you) about our position wrt the Lena stuff, but the decision is entirely yours in the end.

**Comment by rjw57** [comment]
OK. I'll see how much work it is to replace the image since it'd be nice not to have a diff w.r.t. Debian if one can help it. (Sorry for the delay in replying, I've been away from work for a bit and dtcwt == work.)

**Comment by rjw57** [comment]
Turned out that it was mostly just grunt work of repeatedly ``git grep``-ing and fixing up references. I borrowed someone's MATLAB install at work to re-generate the verification data and #111 shoudl address this issue.

Assuming tests pass, etc, the next release of dtcwt should lack Lena in both docs and source tree. Is it useful to you to spin a new minor version release?

**Comment by ghisvail** [comment]
Probably not. I'll just wait for the next stable release.

**Comment by ghisvail** [comment]
Thanks for addressing this btw.

**Comment by rjw57** [comment]
No probs. Although now I'm finding that Travis CI no-longer supports the tricks I was using to test OpenCL... :)
